#基础信息
title: Doing's blog
email: codeitout1024@gmail.com
url: http://doingliaw.github.io
avatar: /assets/img/head.png
description: I'm what i am

#文档配置
markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart

#高亮配置
highlight-theme : my-github

#评论配置
disqus: doingliaw

#统计配置
baidu: eab9e4d1942e2b602b3c9d9972773f27


